name: build

on:
  pull_request:
    branches: [main, dev]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Run tests
      run: |
        python -m pip install --upgrade pip
        pip install python-dateutil pytest
        pytest -v

